-- =============================================================================
-- Live Conflict Ledger — Database Schema (FROZEN CONTRACT)
-- =============================================================================
-- This file is the SINGLE SOURCE OF TRUTH for the database.
-- Apply it to Supabase (SQL Editor -> paste -> run) BEFORE any track begins.
--
-- FROZEN: Do not edit this file without a heads-up to the whole team in chat.
-- Any change here requires regenerating shared/types.ts in the SAME commit
-- (`supabase gen types typescript ... > shared/types.ts`).
--
-- Columns marked "Tier B" are unused during Tier A. They cost nothing empty and
-- exist now so the schema never has to change shape mid-build.
-- =============================================================================

-- Extensions (pgcrypto gives us gen_random_uuid; vector is for Tier B clustering).
create extension if not exists pgcrypto;
create extension if not exists vector;

-- -----------------------------------------------------------------------------
-- sources: every website/institution the system has ever seen.
-- Person A inserts rows. Person B updates discovery_tier + tier_reason.
-- -----------------------------------------------------------------------------
create table if not exists sources (
  id            uuid primary key default gen_random_uuid(),
  domain        text unique not null,
  name          text,
  source_type   text not null default 'news',   -- 'news' | 'institutional_direct' | 'x'
  discovered_via text not null,                  -- exact query string, or literal 'direct:cpj'
  discovery_tier text,                           -- see shared/constants.ts DISCOVERY_TIER
  tier_reason   text,
  created_at    timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- raw_items: one row per scraped article / post.
-- Person A inserts search_discovered + institutional_direct. Person B inserts x.
-- Person C only ever flips `processed` (never edits raw_text/headline).
-- -----------------------------------------------------------------------------
create table if not exists raw_items (
  id            uuid primary key default gen_random_uuid(),
  source_id     uuid not null references sources(id),
  headline      text,
  raw_text      text not null,
  url           text unique not null,            -- unique => dedup by construction
  published_at  timestamptz,
  origin_type   text not null,                   -- 'search_discovered' | 'institutional_direct' | 'x'
  content_shape text not null default 'unknown', -- 'prose' | 'structured' | 'unknown'
  processed     boolean not null default false,  -- Person C: true only after LLM call COMPLETED
  created_at    timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- claims: atomic, append-only facts. Person C owns this table.
-- HARD RULE: raw_quote MUST be a verbatim substring of the parent raw_items.raw_text.
-- HARD RULE: rows are NEVER updated or deleted after insert. Disagreement makes
--            new rows, never mutation.
-- -----------------------------------------------------------------------------
create table if not exists claims (
  id                  uuid primary key default gen_random_uuid(),
  raw_item_id         uuid not null references raw_items(id),
  claim_type          text not null,             -- see shared/constants.ts CLAIM_TYPES
  value               jsonb not null,            -- shape locked per type, see claim_types.md
  raw_quote           text not null,             -- verbatim substring of raw_text
  date_occurred       date,
  location            text,
  lat                 double precision,          -- Tier B: map
  lng                 double precision,          -- Tier B: map
  geo_confidence      float,                     -- Tier B: map
  is_unverified_signal boolean not null default false, -- true for origin_type='x' claims
  created_at          timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- entities: persistent people/places/orgs. Tier B (profiles, per-category views).
-- Person C owns this table.
-- -----------------------------------------------------------------------------
create table if not exists entities (
  id          uuid primary key default gen_random_uuid(),
  entity_type text not null,                     -- 'person' | 'place' | 'org'
  name        text not null,
  subtype     text,                              -- 'journalist' | 'aid_worker' | 'hostage' | 'child' | ...
  metadata    jsonb,
  lat         double precision,
  lng         double precision,
  created_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- claim_entities: link claims to the people/places they're about. Tier B.
-- -----------------------------------------------------------------------------
create table if not exists claim_entities (
  claim_id  uuid not null references claims(id),
  entity_id uuid not null references entities(id),
  primary key (claim_id, entity_id)
);

-- -----------------------------------------------------------------------------
-- events: reconciled clusters of claims. Person C owns this table.
-- has_disagreement / disagreement_note are the Tier A "money demo" fields.
-- -----------------------------------------------------------------------------
create table if not exists events (
  id               uuid primary key default gen_random_uuid(),
  title            text,
  neutral_summary  text,                         -- Tier B
  location         text,
  lat              double precision,             -- Tier B
  lng              double precision,             -- Tier B
  category         text,                         -- strike|casualty|journalist|hostage|displacement|aid
  event_date       date,                         -- Tier B: timeline ordering
  framing_notes    jsonb,                        -- Tier B
  has_disagreement boolean not null default false,
  disagreement_note text,
  first_seen_at    timestamptz not null default now(),
  last_updated_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- event_claims: many-to-many between events and claims. Person C owns this.
-- -----------------------------------------------------------------------------
create table if not exists event_claims (
  event_id uuid not null references events(id),
  claim_id uuid not null references claims(id),
  primary key (event_id, claim_id)
);

-- -----------------------------------------------------------------------------
-- zones: reported "under attack" / evacuation regions. Tier B map layer.
-- Person C owns this. Explicitly NOT an authoritative territorial-control map.
-- -----------------------------------------------------------------------------
create table if not exists zones (
  id           uuid primary key default gen_random_uuid(),
  zone_type    text not null,                    -- 'under_attack' | 'evacuation_order'
  region       text,
  geo_json     jsonb,
  date_observed date,
  source_id    uuid references sources(id),
  raw_quote    text,
  created_at   timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- counter_snapshots: materialized counters so the frontend never aggregates live.
-- Person C owns this. low_value/high_value is a RANGE, never a single point.
-- The tier-gate (COUNTABLE_TIERS) is applied when WRITING these rows — and
-- nowhere else in the system.
-- -----------------------------------------------------------------------------
create table if not exists counter_snapshots (
  id                 uuid primary key default gen_random_uuid(),
  counter_key        text not null,              -- 'journalists_killed', 'palestinians_killed', ...
  as_of_date         date not null,
  low_value          numeric,
  high_value         numeric,
  primary_source_ids uuid[],
  claim_count        int,
  computed_at        timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Helpful indexes (cheap, and the pipeline leans on a couple of these).
-- -----------------------------------------------------------------------------
create index if not exists idx_raw_items_processed  on raw_items (processed);
create index if not exists idx_raw_items_origin      on raw_items (origin_type);
create index if not exists idx_claims_type_date      on claims (claim_type, date_occurred);
create index if not exists idx_sources_tier          on sources (discovery_tier);
create index if not exists idx_snapshots_key_date    on counter_snapshots (counter_key, as_of_date);

-- -----------------------------------------------------------------------------
-- Public read policies for the anon API.
-- -----------------------------------------------------------------------------
-- This is a public transparency product: the API reads through the Supabase anon
-- key and exposes only read endpoints. Writes remain service-role only.
alter table sources enable row level security;
drop policy if exists sources_anon_read on sources;
create policy sources_anon_read on sources
  for select to anon
  using (true);

alter table raw_items enable row level security;
drop policy if exists raw_items_anon_read on raw_items;
create policy raw_items_anon_read on raw_items
  for select to anon
  using (true);

alter table claims enable row level security;
drop policy if exists claims_anon_read on claims;
create policy claims_anon_read on claims
  for select to anon
  using (true);

alter table counter_snapshots enable row level security;
drop policy if exists counter_snapshots_anon_read on counter_snapshots;
create policy counter_snapshots_anon_read on counter_snapshots
  for select to anon
  using (true);
